Update install script
Update SSH version detection. Now
correctly detects the SSH version on
CentOS 7.

diff --git a/install.sh.in b/install.sh.in
--- a/install.sh.in
+++ b/install.sh.in
@@ -15,10 +15,31 @@ f_install()
 
 f_set_env()
 {
-    SSH_MAJOR_VERSION=$(ssh -v 2>&1 | head -1 | awk '{print $1}' | awk -F_ '{print $NF}' | cut -b 1-3 | awk -F. '{print $1}')
-    SSH_MINOR_VERSION=$(ssh -v 2>&1 | head -1 | awk '{print $1}' | awk -F_ '{print $NF}' | cut -b 1-3 | awk -F. '{print $2}')
-    SSH_CMD=$(which ssh 2> /dev/null)
+    if [[ -f /etc/centos-release ]]; then
+        SSH_MAJOR_VERSION="$(rpm -qi openssh-clients | grep ^Version | awk -F: '{print $2}' | sed -e 's/ //g' | cut -b 1-3 | awk -F. '{print $1}')"
+        SSH_MINOR_VERSION="$(rpm -qi openssh-clients | grep ^Version | awk -F: '{print $2}' | sed -e 's/ //g' | cut -b 1-3 | awk -F. '{print $2}')"
+    elif [[ -f /etc/redhat-release ]]; then
+        SSH_MAJOR_VERSION="$(rpm -qi openssh-clients | grep ^Version | awk -F: '{print $2}' | sed -e 's/ //g' | cut -b 1-3 | awk -F. '{print $1}')"
+        SSH_MINOR_VERSION="$(rpm -qi openssh-clients | grep ^Version | awk -F: '{print $2}' | sed -e 's/ //g' | cut -b 1-3 | awk -F. '{print $2}')"
+    elif [[ -f /etc/debian_version ]]; then
+        SSH_MAJOR_VERSION="$(dpkg -s openssh-client | grep ^Version: | awk -F: '{print $3}' | cut -b 1-3 | awk -F. '{print $1}')"
+        SSH_MINOR_VERSION="$(dpkg -s openssh-client | grep ^Version: | awk -F: '{print $3}' | cut -b 1-3 | awk -F. '{print $2}')"
+    else
+        SSH_MAJOR_VERSION=""
+        SSH_MINOR_VERSION=""
+    fi
 
+    if [[ -z $SSH_MAJOR_VERSION ]]; then
+        echo "FATAL ERROR: count not determine ssh major version"
+        exit 1
+    fi
+
+    if [[ -z $SSH_MINOR_VERSION ]]; then
+        echo "FATAL ERROR: count not determine ssh minor version"
+        exit 1
+    fi
+
+    SSH_CMD=$(which ssh 2> /dev/null)
     GIT_CMD=$(which git 2> /dev/null)
 }
 
